exp_name: "beitv2_large_patch16_224.in1k_ft_in22k_in1k"
seed: 111
traindata_dir: './data/train'
testdata_dir: './data/test'

traindata_info_file: './data/train.csv'
testdata_info_file: './data/test.csv'

train_result_path: './train_result'
test_result_path: './output'

transform:
  transform_type: albumentations
  augmentations:
    - type: Rotate
      params:
        limit: 30
        p: 0.5
    - type: HorizontalFlip
      params:
        p: 0.5
    - type: VerticalFlip
      params:
        p: 0.5
    - type: ShiftScaleRotate
      params:
        shift_limit: 0.0625
        scale_limit: 0.1
        rotate_limit: 15
        p: 0.5
    - type: GaussNoise
      params:
        var_limit: [10.0, 50.0]
        mean: 0
        p: 0.5

device: 'cuda'

model_type: 'timm'
model_name: 'beitv2_large_patch16_224.in1k_ft_in22k_in1k'
pretrained: true

loss: 'SmoothingLoss'

lora:
  use: true
  params:
    r: 8
    lora_alpha: 16
    lora_dropout: 0.1
    target_modules: '.*(attn.qkv|attn.proj|mlp.fc\d)'
    modules_to_save: ["head"]

optimizer:
  type: AdamW
  params:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1.0e-8
    amsgrad: False


scheduler:
  type: CosineAnnealingLR
  params:
    T_max: 10
    eta_min: 1.0e-6

num_epochs: 10
batch_size: 64
