exp_name: "ES3_ConvNeXt_base_4"
seed: 999
traindata_dir: './data/train'
testdata_dir: './data/test'

traindata_info_file: './data/train.csv'
testdata_info_file: './data/test.csv'

train_result_path: './train_result'
test_result_path: './output'

# transform:
#   transform_type: albumentations
#   augmentations:
#     - type: HorizontalFlip
#       params:
#         p: 0.3
#     - type: Rotate
#       params:
#         limit: 30
#         p: 0.7
#     - type: RandomBrightnessContrast
#       params:
#         brightness_limit: 0.3
#         contrast_limit: 0.3
#         p: 0.3
#     - type: CLAHE
#       params:
#         p: 0.3
#     - type: Blur
#       params: 
#         blur_limit: 61 
#         p: 0.1

transform:
  transform_type: albumentations
  augmentations:
    - type: Rotate
      params:
        limit: [-120, 120]
        p: 0.5
        border_mode: 1
    - type: HorizontalFlip
      params:
        p: 0.5
    - type: VerticalFlip
      params:
        p: 0.5
    - type: GaussNoise
      params:
        var_limit: [10.0, 50.0]
        mean: 0
        per_channel: true
        noise_scale_factor: 1
        p: 0.5
    - type: LongestMaxSize
      params:
        max_size: 224
    - type: PadIfNeeded
      params:
        min_height: 224
        min_width: 224
        border_mode: 0
        value: 255
    - type: RandomResizedCrop
      params:
        height: 224
        width: 224
        scale: [0.4, 0.8]
        ratio: [0.5, 1.5]
        p: 0.5
    - type: CoarseDropout
      params:
        p: 0.5
        max_holes: 8
        max_height: 60
        max_width: 60
        min_holes: 8
        min_height: 45
        min_width: 45
        fill_value: [255,255,255]


device: 'cuda'

model_type: 'torchvision'
model_name: 'convnext_base'
pretrained: true

loss: 'SmoothingLoss'

optimizer:
  type: AdamW
  params:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1.0e-8
    amsgrad: False

scheduler:
  type: CosineAnnealingLR
  params:
    T_max: 10
    eta_min: 1.0e-6


num_epochs: 5
batch_size: 128

#ES 추가
patience: 10
min_delta: 0.0002