batch_size: 128
device: cuda
exp_name: ES3_ConvNeXt_base_4
loss:
  alpha: 0.25
  gamma: 2
  size_average: true
  type: FocalLoss
min_delta: 0.0002
model_name: convnext_base
model_type: torchvision
num_epochs: 5
optimizer:
  params:
    amsgrad: false
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 0.001
  type: AdamW
patience: 10
pretrained: true
scheduler:
  params:
    T_max: 10
    eta_min: 1.0e-06
  type: CosineAnnealingLR
seed: 999
test_result_path: ./output
testdata_dir: ./data/test
testdata_info_file: ./data/test.csv
train_result_path: ./train_result
traindata_dir: ./data/train
traindata_info_file: ./data/train.csv
transform:
  augmentations:
  - params:
      border_mode: 1
      limit:
      - -120
      - 120
      p: 0.5
    type: Rotate
  - params:
      p: 0.5
    type: HorizontalFlip
  - params:
      p: 0.5
    type: VerticalFlip
  - params:
      mean: 0
      noise_scale_factor: 1
      p: 0.5
      per_channel: true
      var_limit:
      - 10.0
      - 50.0
    type: GaussNoise
  - params:
      max_size: 224
    type: LongestMaxSize
  - params:
      border_mode: 0
      min_height: 224
      min_width: 224
      value: 255
    type: PadIfNeeded
  - params:
      height: 224
      p: 0.5
      ratio:
      - 0.5
      - 1.5
      scale:
      - 0.4
      - 0.8
      width: 224
    type: RandomResizedCrop
  - params:
      fill_value:
      - 255
      - 255
      - 255
      max_height: 60
      max_holes: 8
      max_width: 60
      min_height: 45
      min_holes: 8
      min_width: 45
      p: 0.5
    type: CoarseDropout
  transform_type: albumentations
