exp_name: "dinov2_vitl14_reg_lc"
seed: 999
traindata_dir: './data/train'
testdata_dir: './data/test'

traindata_info_file: './data/train.csv'
testdata_info_file: './data/test.csv'

train_result_path: './train_result'
test_result_path: './output'

transform:
  transform_type: randaugment
  augmentations:


device: 'cuda'

model_type: 'hub'
model_name: 'dinov2_vitl14_reg_lc'
pretrained: true

loss: 'SmoothingLoss'

lora:
  use: true
  params:
    r: 8
    lora_alpha: 16
    lora_dropout: 0.1
    target_modules: '.*(attn.qkv|attn.proj|mlp.fc\d)'
    modules_to_save: ["linear_head"]

optimizer:
  type: AdamW
  params:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1.0e-8
    amsgrad: False


scheduler:
  type: CosineAnnealingLR
  params:
    T_max: 20
    eta_min: 0.000001

num_epochs: 10
batch_size: 32
