exp_name: "autoaug"
seed: 999
traindata_dir: './data/train'
testdata_dir: './data/test'

traindata_info_file: './data/train.csv'
testdata_info_file: './data/test.csv'

train_result_path: './train_result'
test_result_path: './output'

transform:
  transform_type: autoaugment
  augmentations:


device: 'cuda'

model_type: 'timm'
model_name: 'caformer_b36.sail_in22k_ft_in1k'
pretrained: true

loss: 'SmoothingLoss'

optimizer:
  type: AdamW
  params:
    lr: 0.001


scheduler:
  type: CosineAnnealingLR
  params:
    T_max: 20
    eta_min: 0.000001

num_epochs: 5
batch_size: 64
