exp_name: "ES3_ConvNeXt_base_Focal_5"
seed: 999
traindata_dir: './data/train'
testdata_dir: './data/test'

traindata_info_file: './data/train.csv'
testdata_info_file: './data/test.csv'

train_result_path: './train_result'
test_result_path: './output'

transform:
  transform_type: albumentations
  augmentations:
    - type: HorizontalFlip
      params:
        p: 0.3
    - type: Rotate
      params:
        limit: 30
        p: 0.7
    - type: RandomBrightnessContrast
      params:
        brightness_limit: 0.3
        contrast_limit: 0.3
        p: 0.3
    - type: CLAHE
      params:
        p: 0.3
    - type: Blur
      params: 
        blur_limit: 61 
        p: 0.1


device: 'cuda'

model_type: 'torchvision'
model_name: 'convnext_base'
pretrained: true

loss:
  type: 'FocalLoss'
  params:
    gamma: 2
    alpha: 0.25
    reduction: mean # loss를 평균으로 계산

optimizer:
  type: AdamW
  params:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1.0e-8
    amsgrad: False

scheduler:
  type: CosineAnnealingLR
  params:
    T_max: 10
    eta_min: 1.0e-6


num_epochs: 5
batch_size: 128

#ES 추가
patience: 10
min_delta: 0.0002